In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Data available at: https://www.kaggle.com/sootersaalu/exploratory-data-analysis
df = pd.read_csv("bestsellers with categories.csv")
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [5]:
df['Reviews'].sort_values(ascending=False)

534    87841
383    79446
382    79446
33     61133
32     61133
       ...
359      440
512      438
121      408
300      220
78        37
Name: Reviews, Length: 550, dtype: int64

In [6]:
#To overwrite the object?
data_order = df.groupby(['Name', 'Author'], as_index = False)[['User Rating','Reviews']].mean()
data_order = data_order[data_order['Reviews'] > 3000]
data_order = data_order.sort_values('User Rating', ascending=False)
data_order.head(20)

,Name,Author,User Rating,Reviews
177,Obama: An Intimate Portrait,Pete Souza,4.9,3192.0
71,Dog Man: Lord of the Fleas: From the Creator o...,Dav Pilkey,4.9,5470.0
118,Harry Potter and the Goblet of Fire: The Illus...,J. K. Rowling,4.9,7758.0
119,Harry Potter and the Prisoner of Azkaban: The ...,J.K. Rowling,4.9,3146.0
120,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,4.9,10052.0
112,Hamilton: The Revolution,Lin-Manuel Miranda,4.9,5867.0
108,"Goodnight, Goodnight Construction Site (Hardco...",Sherri Duskey Rinker,4.9,7038.0
66,Dog Man and Cat Kid: From the Creator of Capta...,Dav Pilkey,4.9,5062.0
36,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344.0
312,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842.0
67,Dog Man: A Tale of Two Kitties: From the Creat...,Dav Pilkey,4.9,4786.0
208,Strange Planet (Strange Planet Series),Nathan W. Pyle,4.9,9382.0
68,Dog Man: Brawl of the Wild: From the Creator o...,Dav Pilkey,4.9,7235.0
69,Dog Man: Fetch-22: From the Creator of Captain...,Dav Pilkey,4.9,12619.0
70,Dog Man: For Whom the Ball Rolls: From the Cre...,Dav Pilkey,4.9,9089.0
116,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,4.9,19622.0
197,Rush Revere and the First Patriots: Time-Trave...,Rush Limbaugh,4.9,3836.0
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0
196,Rush Revere and the Brave Pilgrims: Time-Trave...,Rush Limbaugh,4.9,7150.0
267,The Legend of Zelda: Hyrule Historia,Patrick Thorpe,4.9,5396.0

In [9]:
#Weighted Rating
m = min(df['Reviews'])
C = df['User Rating'].mean()

def weighted_rating(x, m=m, C = C):
    v = x['Reviews']
    R = x['User Rating']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [13]:
df['Weighted Rating'] = df.apply(weighted_rating, axis = 1)

In [17]:

df.groupby(['Name', "Author", 'Genre'], as_index = False)[['User Rating', 'Reviews', 'Weighted Rating']].mean().sort_values(by = 'Weighted Rating', ascending = False).head(10)

,Name,Author,Genre,User Rating,Reviews,Weighted Rating
178,"Oh, the Places You'll Go!",Dr. Seuss,Fiction,4.9,21834.0,4.899524
116,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,Fiction,4.9,19622.0,4.899470
140,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,Non Fiction,4.9,19576.0,4.899469
310,The Very Hungry Caterpillar,Eric Carle,Fiction,4.9,19546.0,4.899468
36,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,Fiction,4.9,14344.0,4.899275
69,Dog Man: Fetch-22: From the Creator of Captain...,Dav Pilkey,Fiction,4.9,12619.0,4.899177
151,Last Week Tonight with John Oliver Presents A ...,Jill Twiss,Fiction,4.9,11881.0,4.899126
120,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,Fiction,4.9,10052.0,4.898967
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,Fiction,4.9,9413.0,4.898897
208,Strange Planet (Strange Planet Series),Nathan W. Pyle,Fiction,4.9,9382.0,4.898894